data:
  preprocess: standardize
  features:
    - j_zlogz
    - j_c1_b0_mmdt
    - j_c1_b1_mmdt
    - j_c1_b2_mmdt
    - j_c2_b1_mmdt
    - j_c2_b2_mmdt
    - j_d2_b1_mmdt
    - j_d2_b2_mmdt
    - j_d2_a1_b1_mmdt
    - j_d2_a1_b2_mmdt
    - j_m2_b1_mmdt
    - j_m2_b2_mmdt
    - j_n2_b1_mmdt
    - j_n2_b2_mmdt
    - j_mass_mmdt
    - j_multiplicity

model:
  quant_input: 
    activation_bit: 6
  dense_1:
    weight_bit: 4
    bias_bit: 4
  quant_act_1:
    activation_bit: 6
  dense_2:
    weight_bit: 4
    bias_bit: 4
  quant_act_2:
    activation_bit: 6
  dense_3:
    weight_bit: 4
    bias_bit: 4
  quant_act_3:
    activation_bit: 6
  dense_4:
    weight_bit: 4
    bias_bit: 4
